In [ ]:
jovian pip install >>>saves jupyter files

In [9]:
one_hundreth=1e-3  #1/(10^3)
print(one_hundreth)

0.001


In [11]:
type(one_hundreth)

float

In [12]:
avogadro_number=6.0221406e23   #e=10^23
avogadro_number

6.0221406e+23

In [13]:
5+ False

5

In [14]:
3.+ True

4.0

In [15]:
string="hello world"
list(string)

['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']

In [16]:
len(string)

11

In [18]:
greeting="Hello"
fullname="rubina"
greeting + " "+ fullname + "!"

'Hello rubina!'

In [ ]:
dict.keys()
dict.values()
dict.items()
dict.items()[1]


# Data Analysis

In [20]:
import jovian 

ModuleNotFoundError: No module named 'jovian'

In [ ]:
jovian.commit(project='Data Analysis,pandas,numpy,matplotlib,seaborn')

In [24]:
line='*'
max_length=10

while len(line)<=max_length:
    print(line)
    line=line+"*"
    
while len(line)>0:
    print(line)
    line=line[:-1]

*
**
***
****
*****
******
*******
********
*********
**********
***********
**********
*********
********
*******
******
*****
****
***
**
*


In [22]:
string="rubina"
string[:-1]

'rubin'

In [29]:
def loan_emi(amount):
    emi=amount/12
    print('the emi is ${}'.format(emi))
loan_emi(1200000)

def loan_emi1(amount,duration):
    emi1=amount/duration
    print("the amount is ${}".format(emi1))
loan_emi1(12000,5)

the emi is $100000.0
the amount is $2400.0


# EMI=[P* R*(1+R)^N]/((1+R)^N)-1


P IS THE LOAN AMOUNT
N IS NO. OF MONTHS
R IS INTEREST


In [33]:
def loan_emi(amount,duration,rate,down_payment=0):
    loan_amount=amount - down_payment
    emi=loan_amount* rate*((1+rate)**duration)/ (((1+rate)**duration)-1)
    emi=math.ceil(emi)
    return emi
loan_emi(1.26e6,12,0.1/12,3e5)

84400

In [31]:
import math
help(math.ceil)

Help on built-in function ceil in module math:

ceil(x, /)
    Return the ceiling of x as an Integral.
    
    This is the smallest integer >= x.



In [32]:
math.ceil(1.2)

2

In [38]:
math.ceil(2.00001)

3

In [ ]:
2:7:13

In [ ]:
def loan_emi(amount,duration,rate,down_payment=0):
    loan_amount=amount - down_payment
    try:
        emi=loan_amount* rate*((1+rate)**duration)/ (((1+rate)**duration)-1)
    except ZerodivisionError:
        emi=loan_amount/duration
    emi=math.ceil(emi)
    return emi
loan_emi(1.26e6,12,0.1/12,3e5)

In [ ]:
#2:23 has to be done today

In [ ]:
#3:11: has to be done

In [1]:
import numpy as np

In [2]:
kanto=np.array([73,67,43])

In [3]:
kanto

array([73, 67, 43])

In [8]:
weights=np.array([w1,w2,w3])

SyntaxError: invalid syntax (<ipython-input-8-a8104087cec1>, line 1)

In [12]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [17]:
#python lists
arr1=list(range(1000000))
arr2=list(range(100000,2000000))

#Numpy arrays
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [18]:
%%time
result=0
for x1,x2 in zip(arr1,arr2):
    result+=x1*x2
result

Wall time: 313 ms


383332783333500000

In [23]:
import numpy as np
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

%%time
np.dot(arr1_np, arr2_np)

UsageError: Line magic function `%%time` not found.


# other ways to create numpy arrays

In [24]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
#identity maatrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#random matrix   #the difference bw rand(takes values uniformy 0 to 1)and randn(pick values from gaussian distribution)
np.random.randn(5)

array([-0.52016488,  0.47279246,  1.05946538, -0.60413646,  2.42630317])

In [29]:
np.random.rand(2,3)

array([[0.75573244, 0.15612153, 0.14267959],
       [0.51110309, 0.65360486, 0.34089038]])

In [30]:
#fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [31]:
#range with start, end, step
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])